apiVersion: v1
kind: Service
metadata:
  name: ipam-app-service
  labels:
    app: ipam-app
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5001
      nodePort: 30001
  selector:
    app: ipam-app