replicaCount: 5

image:
  repository: ipam/manager
  pullPolicy: IfNotPresent
  tag: "1.0.0"  

env:
  flaskEnv: "development"  # 

imagePullSecrets: []  # Secrets pour pull l'image (si nécessaire)
nameOverride: ""  # Override du nom de l'application
fullnameOverride: ""  # Override du nom complet de l'application

serviceAccount:
  create: true  # Créer un ServiceAccount
  automount: true  # Monter les credentials du ServiceAccount
  annotations: {}  # Annotations pour le ServiceAccount
  name: ""  # Nom du ServiceAccount (optionnel)

podAnnotations: {}  # Annotations pour les pods
podLabels: {}  # Labels supplémentaires pour les pods

podSecurityContext: {}  # Contexte de sécurité pour les pods
  # fsGroup: 2000

securityContext: {}  # Contexte de sécurité pour le conteneur
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: NodePort
  port: 5000
  targetPort: 5000
  nodePort: 30001

ingress:
  enabled: false  # Désactiver Ingress par défaut
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}  # Ressources pour les conteneurs
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

livenessProbe:
  httpGet:
    path: /  # Chemin pour la sonde de liveness
    port: http  # Port pour la sonde de liveness

readinessProbe:
  httpGet:
    path: /  # Chemin pour la sonde de readiness
    port: http  # Port pour la sonde de readiness

autoscaling:
  enabled: false  # Désactiver l'autoscaling par défaut
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Volumes supplémentaires pour le déploiement
volumes:
  - name: app-data
    hostPath:
      path: /data

# Montages de volumes supplémentaires pour les conteneurs
volumeMounts:
  - name: app-data
    mountPath: /app/data

nodeSelector: {}  
tolerations: []
affinity: {}